# Generated by Django 3.1 on 2020-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=30)),
                ('ultimoNome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('dataNascimento', models.DateField()),
            ],
        ),
    ]
