# Generated by Django 3.1 on 2020-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20200821_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='acessarSistema',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
